#:schema node_modules/wrangler/config-schema.json
name = "corecms"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "CORECMS_DB"
database_name = "corecms_db"
database_id = "59366b44-ad7e-4e2c-8540-467c135fa066"
